version: "3"

services:
  livekit:
    image: livekit/livekit-server  # LiveKit 서버 공식 이미지
    ports:
      - "7880:7880"               # ✅ WebSocket 시그널링 포트 (클라이언트가 room.connect() 할 때 사용하는 포트)
      - "7881:7881"               # ✅ ICE TCP 포트 (일부 네트워크에서 UDP가 차단된 경우 fallback용)
      - "7882:7882/udp"           # ✅ 기본 ICE UDP 포트 (미디어 송수신용)
      - "30000-30010:30000-30010/udp"  # ✅ ICE 미디어용 UDP 후보 포트 범위 (여러 참가자 처리용)
        # ⚠️ 확장 시: 이 범위를 더 넓혀야 대규모 다자간 통화 처리 가능
        # 예: "50000-60000:50000-60000/udp"

    environment:
      - LIVEKIT_API_KEY=devkey      # ✅ LiveKit용 API 키 (서버에서 토큰 생성 시 사용)
      - LIVEKIT_API_SECRET=secret   # ✅ LiveKit용 API 시크릿 키 (토큰 서명에 사용)
      
      - LIVEKIT_UDP_PORT=7882       # ✅ STUN/ICE 미디어 포트 (단일 포트 ICE 처리용)
        # ⚠️ 확장 시에는 포트 하나보다 포트 범위(LIVEKIT_UDP_PORT_RANGE) 사용 권장

      - LIVEKIT_UDP_PORT_RANGE=30000-30010  # ✅ 미디어용 UDP 포트 후보 범위 (ICE 후보용)
        # ⚠️ 확장 시 이 범위는 더 넓게 잡을 것
        # 예: 30000-60000 또는 50000-60000

      - LIVEKIT_PUBLIC_IP=host.docker.internal  
        # ✅ 클라이언트에게 전달될 ICE 후보 주소
        # ⚠️ 현재는 **로컬 개발용** 설정
        # ⚠️ 실 서비스 시에는 공인 IP 또는 도메인으로 변경해야 함
        # 예: LIVEKIT_PUBLIC_IP=13.124.xxx.xxx
        # 또는 nginx를 통해 wss 도메인 reverse proxy 구성 필요

    command: ["--dev", "--bind", "0.0.0.0"]
      # ✅ --dev : 개발 모드로 실행 (자동 TURN/STUN 활성화, 보안 제한 완화)
      # ✅ --bind 0.0.0.0 : 외부에서도 이 컨테이너 접근 가능하도록 모든 인터페이스에 바인딩
      # ⚠️ 실서비스에서는 --dev 제거하고 YAML 설정 파일(--config /livekit.yaml) 기반 실행 권장
