UPDATE places SET category_id = 1 WHERE category_id = 0;

TRUNCATE TABLE categories RESTART IDENTITY;
TRUNCATE TABLE review_tags RESTART IDENTITY CASCADE;

INSERT INTO categories (category_name) VALUES
                                           ('음식점(식당/카페)'),('명소'),('축제'),('공통');


INSERT INTO review_tags(category_id, content) VALUES (4, '친절해요');
INSERT INTO review_tags(category_id, content) VALUES (4, '사진이 잘 나와요');
INSERT INTO review_tags(category_id, content) VALUES (4, '반려동물과 가기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (4, '아이와 가기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (4, '오래 머무르기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (4, '뷰가 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (4, '컨셉이 독특해요');
INSERT INTO review_tags(category_id, content) VALUES (4, '인테리어가 멋져요');
INSERT INTO review_tags(category_id, content) VALUES (4, '가성비가 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (4, '특별한 날 가기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (4, '관리가 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (4, '가격이 합리적이에요');
INSERT INTO review_tags(category_id, content) VALUES (4, '편의시설이 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (4, '감각적이에요');
INSERT INTO review_tags(category_id, content) VALUES (4, '맞춤 제작을 잘해요');
INSERT INTO review_tags(category_id, content) VALUES (4, '포장이 정성스러워요');
INSERT INTO review_tags(category_id, content) VALUES (4, '원데이 클래스가 알차요');
INSERT INTO review_tags(category_id, content) VALUES (4, '배달 시스템이 편리해요');
INSERT INTO review_tags(category_id, content) VALUES (4, '파티하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (4, '안전하게 관리해요');
INSERT INTO review_tags(category_id, content) VALUES (4, '샤워실이 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (4, '셔틀버스가 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (4, '숙박하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (4, '야외에서 놀기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (4, '코스가 길어요');
INSERT INTO review_tags(category_id, content) VALUES (4, '부대시설이 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (4, '좌석 간격이 넓어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '매장이 청결해요');
INSERT INTO review_tags(category_id, content) VALUES (1, '화장실이 깨끗해요');
INSERT INTO review_tags(category_id, content) VALUES (1, '주차하기 편해요');
INSERT INTO review_tags(category_id, content) VALUES (1, '환기가 잘 돼요');
INSERT INTO review_tags(category_id, content) VALUES (1, '좌석이 편해요');
INSERT INTO review_tags(category_id, content) VALUES (1, '아늑해요');
INSERT INTO review_tags(category_id, content) VALUES (1, '차분한 분위기예요');
INSERT INTO review_tags(category_id, content) VALUES (1, '음악이 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (1, '야외공간이 멋져요');
INSERT INTO review_tags(category_id, content) VALUES (1, '대화하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (1, '매장이 넓어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '단체모임 하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (1, '음식이 빨리 나와요');
INSERT INTO review_tags(category_id, content) VALUES (1, '샐러드바가 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '직접 잘 구워줘요');
INSERT INTO review_tags(category_id, content) VALUES (1, '포장이 깔끔해요');
INSERT INTO review_tags(category_id, content) VALUES (1, '룸이 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '음료가 맛있어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '잡내가 적어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '코스요리가 알차요');
INSERT INTO review_tags(category_id, content) VALUES (1, '반찬이 잘 나와요');
INSERT INTO review_tags(category_id, content) VALUES (1, '건강한 맛이에요');
INSERT INTO review_tags(category_id, content) VALUES (1, '기본 안주가 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (1, '집중하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (1, '음식이 맛있어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '재료가 신선해요');
INSERT INTO review_tags(category_id, content) VALUES (1, '양이 많아요');
INSERT INTO review_tags(category_id, content) VALUES (1, '특별한 메뉴가 있어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '현지 맛에 가까워요');
INSERT INTO review_tags(category_id, content) VALUES (1, '메뉴 구성이 알차요');
INSERT INTO review_tags(category_id, content) VALUES (1, '비싼 만큼 가치있어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '고기 질이 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (1, '술이 다양해요');
INSERT INTO review_tags(category_id, content) VALUES (1, '커피가 맛있어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '디저트가 맛있어요');
INSERT INTO review_tags(category_id, content) VALUES (1, '향신료가 강하지 않아요');
INSERT INTO review_tags(category_id, content) VALUES (1, '혼밥하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (1, '혼술하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (1, '라이브공연이 훌륭해요');
INSERT INTO review_tags(category_id, content) VALUES (2, '경치가 아름다워요');
INSERT INTO review_tags(category_id, content) VALUES (2, '자연 경관이 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '역사적인 가치가 있어요');
INSERT INTO review_tags(category_id, content) VALUES (2, '사진 명소예요');
INSERT INTO review_tags(category_id, content) VALUES (2, '접근성이 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '사람이 적어 한적해요');
INSERT INTO review_tags(category_id, content) VALUES (2, '설명이 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (2, '체험하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '계절마다 매력이 달라요');
INSERT INTO review_tags(category_id, content) VALUES (2, '산책하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '입장료가 저렴해요');
INSERT INTO review_tags(category_id, content) VALUES (2, '가족과 가기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '자연을 느끼기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '특별한 전시가 있어요');
INSERT INTO review_tags(category_id, content) VALUES (2, '야경이 멋져요');
INSERT INTO review_tags(category_id, content) VALUES (2, '교통이 편리해요');
INSERT INTO review_tags(category_id, content) VALUES (2, '역사/문화 체험이 가능해요');
INSERT INTO review_tags(category_id, content) VALUES (2, '현지 분위기를 느낄 수 있어요');
INSERT INTO review_tags(category_id, content) VALUES (2, '안전하게 관람할 수 있어요');
INSERT INTO review_tags(category_id, content) VALUES (2, '붐비지 않아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '트렌디해요');
INSERT INTO review_tags(category_id, content) VALUES (2, '피크닉하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '신기한 식물이 많아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '근처에 갈 곳이 많아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '산책로가 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (2, '동물 관리가 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (2, '유익해요');
INSERT INTO review_tags(category_id, content) VALUES (2, '대기시간이 짧아요');
INSERT INTO review_tags(category_id, content) VALUES (2, '규모가 커요');
INSERT INTO review_tags(category_id, content) VALUES (3, '분위기가 활기차요');
INSERT INTO review_tags(category_id, content) VALUES (3, '분위기가 열정적이에요');
INSERT INTO review_tags(category_id, content) VALUES (3, '공연이 재미있어요');
INSERT INTO review_tags(category_id, content) VALUES (3, '먹거리가 다양해요');
INSERT INTO review_tags(category_id, content) VALUES (3, '볼거리가 많아요');
INSERT INTO review_tags(category_id, content) VALUES (3, '체험 부스가 풍부해요');
INSERT INTO review_tags(category_id, content) VALUES (3, '지역 특색이 느껴져요');
INSERT INTO review_tags(category_id, content) VALUES (3, '프로그램 구성이 알차요');
INSERT INTO review_tags(category_id, content) VALUES (3, '가족 단위로 즐기기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (3, '아이들이 좋아해요');
INSERT INTO review_tags(category_id, content) VALUES (3, '야간에도 즐길 수 있어요');
INSERT INTO review_tags(category_id, content) VALUES (3, '이벤트가 풍성해요');
INSERT INTO review_tags(category_id, content) VALUES (3, '굿즈가 다양해요');
INSERT INTO review_tags(category_id, content) VALUES (3, '사람들이 많이 모여요');
INSERT INTO review_tags(category_id, content) VALUES (3, '안전 관리가 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (3, '교통편이 잘 되어있어요');
INSERT INTO review_tags(category_id, content) VALUES (3, '지역 주민과 소통하기 좋아요');
INSERT INTO review_tags(category_id, content) VALUES (3, '계절마다 색다른 매력이 있어요');
INSERT INTO review_tags(category_id, content) VALUES (3, '축제 장소가 넓어요');
INSERT INTO review_tags(category_id, content) VALUES (3, '현지 문화를 깊이 체험할 수 있어요');